# This image is broken because of https://github.com/qbittorrent/docker-qbittorrent-nox/issues/50.

FROM ghcr.io/qbittorrent/docker-qbittorrent-nox:5.0.1-1

ENV QBT_LEGAL_NOTICE=confirm

# Modern Docker installations are rootless.
ENV PUID=0
ENV PGID=0

COPY ./config/ /config/qBittorrent/config/