MODEL_RESNET18 = "RESNET18"
MODEL_CNN = "CNN"
MODEL_BERT= "BERT"
DATASET_COFAR10="CIFAR10"
DATASET_CIFAR100 = "CIFAR100"

DATASET_MNIST="MNIST"
DATASET_IMDB="IMDB"
DATASET_AG_NEWS = "AG_NEWS"
BERT_BASE="base"
BERT_LARGE="large"



MODEL_RESNET50 = "RESNET50"

